version: '3.4'

services:
  db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "nbiFWtJ8gT31eABE2nHMZB1r8OTId3mFwkJjcJMquibzuM3X5qzYkDtojRrgz1fLUwa1vJFXo0yNPsgo7FH5YIn2xRmJ6dXjH24"
      ACCEPT_EULA: "Y"